### ISSUE TITLE
SabNZBd

### ISSUE THREAD

**Issue by kr889063** [mdhiggins/sma-mod#5] opened 2021-08-16 14:31 UTC
I am running  SabNZBd from Linuxserver.io and have it pulling in the mod. When a file is download I am getting the below error. 

In SabNZBd I have the categories set to use the SABPostProcess.sh. 

`Traceback (most recent call last):
File "/usr/local/sma/SABPostProcess.py", line 8, in <module>
from resources.mediaprocessor import MediaProcessor
File "/usr/local/sma/resources/mediaprocessor.py", line 12, in <module>
from resources.metadata import Metadata, MediaType
File "/usr/local/sma/resources/metadata.py", line 3, in <module>
import requests
ModuleNotFoundError: No module named 'requests`

Any ideas as it was working fine about 6 to 7 days ago?

**Comment by mediacowboy** [comment] 2021-08-16 14:34
Posted with my school account. Adding my personal account to watch the status.

**Comment by mdhiggins** [comment] 2021-08-16 14:41
This appears to be a duplicate of https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1468, continue discussion there

Not sure what changed that would have caused the requests module to not be installed, haven't made any changes to the requirements

**Closed by mdhiggins** 2021-08-16 14:41 UTC
